//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTreatment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTreatment()
        {
            this.TblTreats = new HashSet<TblTreat>();
            this.TblSummaries = new HashSet<TblSummary>();
        }
    
        public int Treatment_Id { get; set; }
        public System.DateTime Treatment_Date { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public string WasDone { get; set; }
        public int TType_Id { get; set; }
        public int Room_Num { get; set; }
    
        public virtual TblRoom TblRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTreat> TblTreats { get; set; }
        public virtual TblType TblType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSummary> TblSummaries { get; set; }
    }
}
